compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmAlwaysAuth: true

npmAuthIdent: eHNhY0szSE46Z1Nuc01oM1hObWhtRGVxTnNKbUNqRHROYThJdExZVHdFOGtGTlVlNWhON2Y=

npmRegistryServer: "https://nexus.greshamtech.com/repository/npm-group/"
